name: cine_hub
description: A full-featured movie & TV streaming app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  webview_flutter: ^4.4.4
  video_player: ^2.8.2
  chewie: ^1.7.4
  shimmer: ^3.0.0
  logger: ^2.0.2
  intl: ^0.18.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true